# Generated by Django 5.2.7 on 2025-10-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_completed_at_task_priority_alter_task_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
